### ISSUE TITLE
LogTimeout: Cannot read property 'timer' of undefined

### ISSUE THREAD

**Issue by TLaue** [getndazn/dazn-lambda-powertools#82]
# This is a Bug Report

## Description

* What went wrong?
I received the following error "Cannot read property timer of undefined" when runing local integration tests for a lambda function following the strategy presented in the "Production-Ready Serverless" course of "theburningmonk". The code fails at
`    onError: (handler, next) => {
      if (handler.context.lambdaPowertoolsLogTimeoutMiddleware.timer) {
        clearTimeout(handler.context.lambdaPowertoolsLogTimeoutMiddleware.timer)
      }

      next(handler.error)
    }`
as the context object is empty during the integration test.
* What did you expect should have happened?
* What was the config (if any) you used?
Lambda function config:
`handler
  .use(validator({ inputSchema: sqsSchema }))
  .use(sampleLogging({ sampleRate: 0.01 }))
  .use(logTimeout());
`
* What stacktrace or error message did you see?
"TypeError: Cannot read property 'timer' of undefined
    at onError (/home/thomas/projects/alerting/src/messagePublisher/node_modules/@dazn/lambda-powertools-middleware-log-timeout/index.js:38:64)
    at runNext (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:106:24)
    at onError (/home/thomas/projects/alerting/src/messagePublisher/node_modules/@dazn/lambda-powertools-middleware-sample-logging/index.js:35:7)
    at runNext (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:106:24)
    at runErrorMiddlewares (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:130:3)
    at errorHandler (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:160:14)
    at runMiddlewares (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:164:23)
    at runNext (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:87:14)
    at runMiddlewares (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:91:3)
    at instance (/home/thomas/projects/alerting/src/messagePublisher/node_modules/middy/src/middy.js:163:5)"
Similar or dependent issues:
* #12345

## Additional Data

* ***Which powertool package are you using?***:
"dependencies": {
    "@dazn/lambda-powertools-logger": "^1.8.2",
    "@dazn/lambda-powertools-middleware-log-timeout": "^1.8.2",
    "@dazn/lambda-powertools-middleware-sample-logging": "^1.8.2",
    "middy": "^0.28.5"
  },
* ***Which version are you using?***:
* ***Middy engine version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
@TLaue I suspect it might be because the input validation middleware is applied before the log-timeout middleware. So when it runs the order goes `validator` -> `sampleLogging` -> `logTimeout` but when it errors the `onError` execution flow is the other way around.

Can you try:
```
handler
  .use(logTimeout())
  .use(sampleLogging({ sampleRate: 0.01 }))
  .use(validator({ inputSchema: sqsSchema }));
```
and see if it fixes the problem?

We will make the `onError` code more robust and check if the `timer` has been initialized rather than just assume it has.

**Comment by TLaue** [comment]
@theburningmonk I cannot try this out at the moment as I am not at work during the next two weeks but  your assumption sounds reasonable as this problem did not exist prior to including the validator middleware.

**Comment by theburningmonk** [comment]
@TLaue no probs. Let me know how it goes once you've had a chance to test it out. I'll add a ticket to make the `logTimeout` middleware more robust
